AWSTemplateFormatVersion: "2010-09-09"
Description: Definitions of S3, IAM User and KMS

# ------------------------------------------------------------#
# Input Parameters
# ------------------------------------------------------------#
Parameters:
    Chain:
        Default: ethereum
        Type: String
    ValidatorName:
        Default: "yourname"
        Type: String
        AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
        ConstraintDescription: "must begin with a letter and contain only alphanumeric characters."

Resources:
    # ------------------------------------------------------------#
    #  IAM
    # ------------------------------------------------------------#
    IAMUser:
        Type: AWS::IAM::User
        Properties:
            UserName: !Sub "abacus-validator-${Chain}"
            Tags:
                - Key: "Chain"
                  Value: !Ref Chain
                - Key: "Name"
                  Value: !Sub "abacus-validator-${Chain}"

    IAMUserAccessKey:
        Type: AWS::IAM::AccessKey
        DependsOn:
            - IAMUser
        Properties:
            UserName: !Sub "abacus-validator-${Chain}"
    # ------------------------------------------------------------#
    #  KMS
    # ------------------------------------------------------------#
    # Alias
    myAlias:
        Type: "AWS::KMS::Alias"
        Properties:
            AliasName: !Sub alias/abacus-validator-signer-${Chain}
            TargetKeyId: !Ref myKey

    # Key
    myKey:
        Type: "AWS::KMS::Key"
        DependsOn: "IAMUser"
        Properties:
            Description: ECC_SECG_P256K1 asymmetric KMS key for signing and verification
            KeySpec: ECC_SECG_P256K1
            KeyUsage: SIGN_VERIFY
            KeyPolicy:
                Version: "2012-10-17"
                Id: !Sub "key-policy-${Chain}"
                Statement:
                    - Sid: Enable IAM User Permissions
                      Effect: Allow
                      Principal:
                          AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
                      Action: "kms:*"
                      Resource: "*"
                    - Sid: Allow use of the key
                      Effect: Allow
                      Principal:
                          AWS: !GetAtt IAMUser.Arn
                      Action:
                          - "kms:GetPublicKey"
                          - "kms:Sign"
                      Resource: "*"
    # ------------------------------------------------------------#
    #  S3
    # ------------------------------------------------------------#
    # S3 Bucket

    myS3Bucket:
        Type: "AWS::S3::Bucket"
        # DeletionPolicy: "Retain"
        Properties:
            BucketName: !Sub "abacus-validator-signatures-${ValidatorName}-${Chain}"
            OwnershipControls:
                Rules:
                    - ObjectOwnership: BucketOwnerEnforced
            PublicAccessBlockConfiguration:
                BlockPublicAcls: True
                IgnorePublicAcls: True
            Tags:
                - Key: "Chain"
                  Value: !Ref Chain
                - Key: "Name"
                  Value: !Sub "abacus-validator-signatures-${ValidatorName}-${Chain}"

    # S3 Bucket Policy
    S3Policy:
        Type: AWS::S3::BucketPolicy
        DependsOn: "IAMUser"
        Properties:
            Bucket: !Ref "myS3Bucket"
            PolicyDocument:
                Version: "2012-10-17"
                Id: !Sub "abacus-validator-signatures-${ValidatorName}-${Chain}-policy"
                Statement:
                    - Sid: !Sub "abacus-validator-signatures-${ValidatorName}-${Chain}-anyone"
                      Effect: "Allow"
                      Principal: "*"
                      Action:
                          - "s3:GetObject"
                          - "s3:ListBucket"
                      Resource:
                          - !Sub "arn:aws:s3:::abacus-validator-signatures-${ValidatorName}-${Chain}"
                          - !Sub "arn:aws:s3:::abacus-validator-signatures-${ValidatorName}-${Chain}/*"
                    - Sid: !Sub "abacus-validator-signatures-${ValidatorName}-${Chain}-iam"
                      Effect: "Allow"
                      Principal:
                          AWS: !GetAtt IAMUser.Arn
                      Action:
                          - "s3:DeleteObject"
                          - "s3:PutObject"
                      Resource:
                          - !Sub "arn:aws:s3:::abacus-validator-signatures-${ValidatorName}-${Chain}/*"

# ------------------------------------------------------------#
# Output Parameters
# ------------------------------------------------------------#
Outputs:
    AwsAccessKeyId:
        Value: !Ref IAMUserAccessKey

    AwsSecretAccessKey:
        Value: !GetAtt IAMUserAccessKey.SecretAccessKey

    KmsKeyId:
        Value: !Ref myKey

    ValidatorName:
        Value: !Ref ValidatorName

    AbcValidatorCheckpointsyncerBucket:
        Value: !Ref myS3Bucket

    AbcValidatorRegion:
        Value: !Ref AWS::Region

    AbcValidatorCheckpointsyncerRegion:
        Value: !Ref AWS::Region

    AbcBaseValidatorRegion:
        Value: !Ref AWS::Region
