version: "3.8"

services:
  nodejs:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./$CHAIN/.env:/.env
      - ./get-aws-kms-address:/get-aws-kms-address
    command: ts-node index.ts
    tty: true
    working_dir: /get-aws-kms-address
