version: "3.8"
services:
    ethereum:
        image: gcr.io/abacus-labs-dev/abacus-agent:sha-90f1885
        user: 0:0
        command:
            - ./validator
        env_file:
            - chain/ethereum/.env
        environment:
            - RUN_ENV=mainnet
            - BASE_CONFIG=ethereum_config.json
            - ABC_VALIDATOR_VALIDATOR_ID=alias/abacus-validator-signer-ethereum
            - ABC_VALIDATOR_REORGPERIOD=256
            - ABC_VALIDATOR_INTERVAL=15
            - ABC_BASE_VALIDATOR_TYPE=aws
            - ABC_VALIDATOR_CHECKPOINTSYNCER_TYPE=s3
            - ABC_BASE_TRACING_LEVEL=info
            - ABC_VALIDATOR_DB=/app/db
            - ABC_BASE_DB=/app/db
        volumes:
            - ethereum-db:/app/db
    polygon:
        image: gcr.io/abacus-labs-dev/abacus-agent:sha-90f1885
        user: 0:0
        command:
            - ./validator
        env_file:
            - chain/polygon/.env
        environment:
            - RUN_ENV=mainnet
            - BASE_CONFIG=polygon_config.json
            - ABC_VALIDATOR_VALIDATOR_ID=alias/abacus-validator-signer-polygon
            - ABC_VALIDATOR_REORGPERIOD=256
            - ABC_VALIDATOR_INTERVAL=15
            - ABC_BASE_VALIDATOR_TYPE=aws
            - ABC_VALIDATOR_CHECKPOINTSYNCER_TYPE=s3
            - ABC_BASE_TRACING_LEVEL=info
            - ABC_VALIDATOR_DB=/app/db
            - ABC_BASE_DB=/app/db
        volumes:
            - polygon-db:/app/db
    optimism:
        image: gcr.io/abacus-labs-dev/abacus-agent:sha-90f1885
        user: 0:0
        command:
            - ./validator
        env_file:
            - chain/optimism/.env
        environment:
            - RUN_ENV=mainnet
            - BASE_CONFIG=optimism_config.json
            - ABC_VALIDATOR_VALIDATOR_ID=alias/abacus-validator-signer-optimism
            - ABC_VALIDATOR_REORGPERIOD=256
            - ABC_VALIDATOR_INTERVAL=15
            - ABC_BASE_VALIDATOR_TYPE=aws
            - ABC_VALIDATOR_CHECKPOINTSYNCER_TYPE=s3
            - ABC_BASE_TRACING_LEVEL=info
            - ABC_VALIDATOR_DB=/app/db
            - ABC_BASE_DB=/app/db
        volumes:
            - optimism-db:/app/db
    celo:
        image: gcr.io/abacus-labs-dev/abacus-agent:sha-90f1885
        user: 0:0
        command:
            - ./validator
        env_file:
            - chain/celo/.env
        environment:
            - RUN_ENV=mainnet
            - BASE_CONFIG=celo_config.json
            - ABC_VALIDATOR_VALIDATOR_ID=alias/abacus-validator-signer-celo
            - ABC_VALIDATOR_REORGPERIOD=256
            - ABC_VALIDATOR_INTERVAL=15
            - ABC_BASE_VALIDATOR_TYPE=aws
            - ABC_VALIDATOR_CHECKPOINTSYNCER_TYPE=s3
            - ABC_BASE_TRACING_LEVEL=info
            - ABC_VALIDATOR_DB=/app/db
            - ABC_BASE_DB=/app/db
        volumes:
            - celo-db:/app/db
    bsc:
        image: gcr.io/abacus-labs-dev/abacus-agent:sha-90f1885
        user: 0:0
        command:
            - ./validator
        env_file:
            - chain/bsc/.env
        environment:
            - RUN_ENV=mainnet
            - BASE_CONFIG=bsc_config.json
            - ABC_VALIDATOR_VALIDATOR_ID=alias/abacus-validator-signer-bsc
            - ABC_VALIDATOR_REORGPERIOD=256
            - ABC_VALIDATOR_INTERVAL=15
            - ABC_BASE_VALIDATOR_TYPE=aws
            - ABC_VALIDATOR_CHECKPOINTSYNCER_TYPE=s3
            - ABC_BASE_TRACING_LEVEL=info
            - ABC_VALIDATOR_DB=/app/db
            - ABC_BASE_DB=/app/db
        volumes:
            - bsc-db:/app/db
    avalanche:
        image: gcr.io/abacus-labs-dev/abacus-agent:sha-90f1885
        user: 0:0
        command:
            - ./validator
        env_file:
            - chain/avalanche/.env
        environment:
            - RUN_ENV=mainnet
            - BASE_CONFIG=avalanche_config.json
            - ABC_VALIDATOR_VALIDATOR_ID=alias/abacus-validator-signer-avalanche
            - ABC_VALIDATOR_REORGPERIOD=256
            - ABC_VALIDATOR_INTERVAL=15
            - ABC_BASE_VALIDATOR_TYPE=aws
            - ABC_VALIDATOR_CHECKPOINTSYNCER_TYPE=s3
            - ABC_BASE_TRACING_LEVEL=info
            - ABC_VALIDATOR_DB=/app/db
            - ABC_BASE_DB=/app/db
        volumes:
            - avalanche-db:/app/db
    arbitrum:
        image: gcr.io/abacus-labs-dev/abacus-agent:sha-90f1885
        user: 0:0
        command:
            - ./validator
        env_file:
            - chain/arbitrum/.env
        environment:
            - RUN_ENV=mainnet
            - BASE_CONFIG=arbitrum_config.json
            - ABC_VALIDATOR_VALIDATOR_ID=alias/abacus-validator-signer-arbitrum
            - ABC_VALIDATOR_REORGPERIOD=256
            - ABC_VALIDATOR_INTERVAL=15
            - ABC_BASE_VALIDATOR_TYPE=aws
            - ABC_VALIDATOR_CHECKPOINTSYNCER_TYPE=s3
            - ABC_BASE_TRACING_LEVEL=info
            - ABC_VALIDATOR_DB=/app/db
            - ABC_BASE_DB=/app/db
        volumes:
            - arbitrum-db:/app/db
volumes:
    ethereum-db:
    polygon-db:
    optimism-db:
    celo-db:
    bsc-db:
    avalanche-db:
    arbitrum-db:
